<a href="https://colab.research.google.com/github/KoenVanKesteren/colab-test/blob/main/tensorflow-test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [ ]:
# x = tf.constant([[1,2,3],[4,5,6]])
# x = tf.constant(4)
x = tf.range(start=1, limit=30, delta=6)
print(x)

tf.Tensor([ 1  7 13 19 25], shape=(5,), dtype=int32)
tf.Tensor([ 1.  7. 13. 19. 25.], shape=(5,), dtype=float64)


In [ ]:
y = tf.cast(x, dtype=tf.float64)
print(y)

tf.Tensor([ 1.  7. 13. 19. 25.], shape=(5,), dtype=float64)


In [ ]:
# math operations
x = tf.constant([10, 20, 30])
y = tf.constant([2,4,6])

# optellen
z = tf.add(x,y)
# of gewoon: 
z = x + y

print(z)

# vermenigvuldigen
z = tf.multiply(x,y)
# of:
z = x*y

print(z)

# DOT operation
z = tf.tensordot(x, y, axes=1)
print(z)

tf.Tensor([12 24 36], shape=(3,), dtype=int32)
tf.Tensor([ 20  80 180], shape=(3,), dtype=int32)
tf.Tensor(280, shape=(), dtype=int32)


In [ ]:
# matrix multiplication
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))

print(x)
print(y)

z = tf.matmul(x, y)

print(z)

tf.Tensor(
[[-0.6427409  -1.4367982   0.71322614]
 [ 0.20465247  0.6629118  -0.51164395]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 1.9905591   0.6627387   0.13763525 -0.78799325]
 [ 0.25775525 -0.31600538  0.331267    0.6259244 ]
 [-0.5190161   1.5678543   1.4101632   0.28313172]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[-2.0199318   1.1463013   0.4413376  -0.19091465]
 [ 0.8437933  -0.8760357  -0.47373328  0.10880525]], shape=(2, 4), dtype=float32)


In [2]:
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

In [6]:
# de data heeft hier het format van een numpy array
(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(x_train.shape)
print(y_train.shape)

# ipv een 28 x 28 matrix willen we alle input pixels in een enkele laag plaatsen
# en we willen alle waarden normaliseren (tussen 0 en 1) dus delen we door 255 (= max rgb waarde)
x_train = x_train.reshape(-1, 784).astype("float32") / 255.0
print(x_train.shape)
x_test = x_test.reshape(-1, 784).astype("float32") / 255.0


# model trainen
# ...


(60000, 28, 28)
(60000,)
(60000, 784)
Epoch 1/5


/usr/local/lib/python3.7/dist-packages/keras/optimizers/optimizer_v2/adam.py:110: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


1875/1875 - 11s - loss: 0.1874 - accuracy: 0.9427 - 11s/epoch - 6ms/step
Epoch 2/5
1875/1875 - 11s - loss: 0.0786 - accuracy: 0.9745 - 11s/epoch - 6ms/step
Epoch 3/5
1875/1875 - 12s - loss: 0.0542 - accuracy: 0.9828 - 12s/epoch - 6ms/step
Epoch 4/5
1875/1875 - 14s - loss: 0.0412 - accuracy: 0.9866 - 14s/epoch - 8ms/step
Epoch 5/5
1875/1875 - 16s - loss: 0.0317 - accuracy: 0.9895 - 16s/epoch - 8ms/step
313/313 - 1s - loss: 0.0819 - accuracy: 0.9762 - 1s/epoch - 4ms/step


[0.081889808177948, 0.9761999845504761]

In [7]:
# sequential API (very convenient, not very flexible)
model = keras.Sequential(
    [
        keras.Input(shape=784),
        layers.Dense(512, activation='relu'),
        layers.Dense(256, activation='relu'),
        layers.Dense(10)
    ]
)

# OF:
# model = keras.Sequential()
# model.add(keras.Input(shape=784))
# model.add(layers.Dense(512, activation='relu'))
# model.add(layers.Dense(256, activation='relu'))
# model.add(layers.Dense(10))

# print(model.summary())

model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=["accuracy"],
)

model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=2)
model.evaluate(x_test, y_test, batch_size=32, verbose=2)

Epoch 1/5
1875/1875 - 14s - loss: 0.1866 - accuracy: 0.9435 - 14s/epoch - 7ms/step
Epoch 2/5
1875/1875 - 14s - loss: 0.0800 - accuracy: 0.9756 - 14s/epoch - 8ms/step
Epoch 3/5
1875/1875 - 14s - loss: 0.0558 - accuracy: 0.9824 - 14s/epoch - 8ms/step
Epoch 4/5
1875/1875 - 14s - loss: 0.0397 - accuracy: 0.9872 - 14s/epoch - 7ms/step
Epoch 5/5
1875/1875 - 14s - loss: 0.0335 - accuracy: 0.9897 - 14s/epoch - 7ms/step
313/313 - 1s - loss: 0.0718 - accuracy: 0.9786 - 1s/epoch - 4ms/step


[0.07179135084152222, 0.978600025177002]

In [9]:
# Functional API (a bit more flexible)

inputs = keras.Input(shape=784)
layer_1 = layers.Dense(512, activation='relu')(inputs)
layer_2 = layers.Dense(256, activation='relu')(layer_1)
outputs = layers.Dense(10)(layer_2)

model = keras.Model(inputs=inputs, outputs=outputs)

model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=["accuracy"],
)

model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=2)
model.evaluate(x_test, y_test, batch_size=32, verbose=2)


Epoch 1/5


/usr/local/lib/python3.7/dist-packages/keras/optimizers/optimizer_v2/adam.py:110: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


1875/1875 - 11s - loss: 0.1880 - accuracy: 0.9426 - 11s/epoch - 6ms/step
Epoch 2/5
1875/1875 - 12s - loss: 0.0804 - accuracy: 0.9751 - 12s/epoch - 6ms/step
Epoch 3/5
1875/1875 - 11s - loss: 0.0560 - accuracy: 0.9826 - 11s/epoch - 6ms/step
Epoch 4/5
1875/1875 - 12s - loss: 0.0415 - accuracy: 0.9872 - 12s/epoch - 6ms/step
Epoch 5/5
1875/1875 - 10s - loss: 0.0331 - accuracy: 0.9897 - 10s/epoch - 6ms/step
313/313 - 1s - loss: 0.0824 - accuracy: 0.9763 - 929ms/epoch - 3ms/step


[0.08243612945079803, 0.9763000011444092]