<a href="https://colab.research.google.com/github/KoenVanKesteren/colab-test/blob/main/tensorflow-test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

In [ ]:
# x = tf.constant([[1,2,3],[4,5,6]])
# x = tf.constant(4)
x = tf.range(start=1, limit=30, delta=6)
print(x)

tf.Tensor([ 1  7 13 19 25], shape=(5,), dtype=int32)
tf.Tensor([ 1.  7. 13. 19. 25.], shape=(5,), dtype=float64)


In [ ]:
y = tf.cast(x, dtype=tf.float64)
print(y)

tf.Tensor([ 1.  7. 13. 19. 25.], shape=(5,), dtype=float64)


In [ ]:
# math operations
x = tf.constant([10, 20, 30])
y = tf.constant([2,4,6])

# optellen
z = tf.add(x,y)
# of gewoon: 
z = x + y

print(z)

# vermenigvuldigen
z = tf.multiply(x,y)
# of:
z = x*y

print(z)

# DOT operation
z = tf.tensordot(x, y, axes=1)
print(z)

tf.Tensor([12 24 36], shape=(3,), dtype=int32)
tf.Tensor([ 20  80 180], shape=(3,), dtype=int32)
tf.Tensor(280, shape=(), dtype=int32)


In [ ]:
# matrix multiplication
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))

print(x)
print(y)

z = tf.matmul(x, y)

print(z)

tf.Tensor(
[[-0.6427409  -1.4367982   0.71322614]
 [ 0.20465247  0.6629118  -0.51164395]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 1.9905591   0.6627387   0.13763525 -0.78799325]
 [ 0.25775525 -0.31600538  0.331267    0.6259244 ]
 [-0.5190161   1.5678543   1.4101632   0.28313172]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[-2.0199318   1.1463013   0.4413376  -0.19091465]
 [ 0.8437933  -0.8760357  -0.47373328  0.10880525]], shape=(2, 4), dtype=float32)


In [3]:
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist
# mnist is de dataset met allemaal handgeschreven cijfers
# 28*28 pixels = 784 input neurons

In [4]:
# de data heeft hier het format van een numpy array
(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(x_train.shape)
print(y_train.shape)

# ipv een 28 x 28 matrix willen we alle input pixels in een enkele laag plaatsen
# en we willen alle waarden normaliseren (tussen 0 en 1) dus delen we door 255 (= max rgb waarde)
x_train = x_train.reshape(-1, 784).astype("float32") / 255.0
print(x_train.shape)
x_test = x_test.reshape(-1, 784).astype("float32") / 255.0


# model trainen
# (zie volgende blokken)


11490434/11490434 [==============================] - 0s 0us/step
(60000, 28, 28)
(60000,)
(60000, 784)


In [5]:
# sequential API (very convenient, not very flexible)
model = keras.Sequential(
    [
        keras.Input(shape=784),
        layers.Dense(512, activation='relu'),
        layers.Dense(256, activation='relu'),
        layers.Dense(10)
    ]
)

# OF:
# model = keras.Sequential()
# model.add(keras.Input(shape=784))
# model.add(layers.Dense(512, activation='relu'))
# model.add(layers.Dense(256, activation='relu'))
# model.add(layers.Dense(10))

# print(model.summary())

model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=["accuracy"],
)

model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=2)
model.evaluate(x_test, y_test, batch_size=32, verbose=2)

Epoch 1/5


/usr/local/lib/python3.7/dist-packages/keras/optimizers/optimizer_v2/adam.py:110: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


1875/1875 - 10s - loss: 0.1866 - accuracy: 0.9430 - 10s/epoch - 6ms/step
Epoch 2/5
1875/1875 - 13s - loss: 0.0798 - accuracy: 0.9750 - 13s/epoch - 7ms/step
Epoch 3/5
1875/1875 - 10s - loss: 0.0525 - accuracy: 0.9833 - 10s/epoch - 5ms/step
Epoch 4/5
1875/1875 - 10s - loss: 0.0421 - accuracy: 0.9868 - 10s/epoch - 5ms/step
Epoch 5/5
1875/1875 - 9s - loss: 0.0349 - accuracy: 0.9883 - 9s/epoch - 5ms/step
313/313 - 1s - loss: 0.0756 - accuracy: 0.9783 - 838ms/epoch - 3ms/step


[0.07563959062099457, 0.9782999753952026]

In [6]:
# Functional API (a bit more flexible)

inputs = keras.Input(shape=784)
layer_1 = layers.Dense(512, activation='relu')(inputs)
layer_2 = layers.Dense(256, activation='relu')(layer_1)
outputs = layers.Dense(10)(layer_2)

model = keras.Model(inputs=inputs, outputs=outputs)

model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=["accuracy"],
)

model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=2)
model.evaluate(x_test, y_test, batch_size=32, verbose=2)



Epoch 1/5
1875/1875 - 10s - loss: 0.1841 - accuracy: 0.9445 - 10s/epoch - 5ms/step
Epoch 2/5
1875/1875 - 9s - loss: 0.0809 - accuracy: 0.9748 - 9s/epoch - 5ms/step
Epoch 3/5
1875/1875 - 11s - loss: 0.0544 - accuracy: 0.9824 - 11s/epoch - 6ms/step
Epoch 4/5
1875/1875 - 10s - loss: 0.0402 - accuracy: 0.9871 - 10s/epoch - 5ms/step
Epoch 5/5
1875/1875 - 10s - loss: 0.0334 - accuracy: 0.9890 - 10s/epoch - 5ms/step
313/313 - 1s - loss: 0.0742 - accuracy: 0.9792 - 894ms/epoch - 3ms/step


[0.0741533488035202, 0.979200005531311]